### ISSUE TITLE
getAccounts() doesn't return info about token holders, where OCEAN tokens are transferred via mint() function

### ISSUE THREAD

**Issue by innoprenuer** [oceanprotocol/ocean-token#15]
We currently have `getAccounts( uint256 _start, uint256 _end )` that returns data about OCEAN token holders and their balances. Data to this function if fed by registry function `updateTokenHolders( address sender, address receiver )`. This registry function is being called in `transfer` and `transferFrom` functions, but is called in `mint` function which essentially is doing transfer underneath. 

As a result, `getAccounts( uint256 _start, uint256 _end )` function only returns data about addresses that used `transfer` and `transferFrom` functions and not `mint` function, which is incorrect as the end goal is to get all the accounts that holds OCEAN tokens.

**Comment by H34D** [comment]
On the first transaction this account will be listed as holder, this is only relevant if we mint tokens to accounts that never going to send a single token. This is not the case.
