### ISSUE TITLE
Definition of ocean-token specifications

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/ocean-token#5]
Before auditing the code it would be necessary to document the requirements of the current Ocean Token implementation. 
This definition should include things like:

- What is the expected usage of this contract?
- What is the expected lifecycle of this contract?
- What are the roles used?
- Why we have this specific cap?
- Why the contract is killable?
- etc

This documentation should be provided in Markdown format as part of the repository. For example included in the README.md file.

**Comment by H34D** [comment]
OceanToken specs right now:

- ERC20
- Mintable (by Owner)
- Ownable (assigned to Owner Wallet)
- Killable
- Fallback function

**Comment by aaitor** [comment]
The idea is to extend that to give a rationale. For example, why is killable? We know the answer but we need to articulate in order to give more clarity about what we expect to have "technically" given those requirements.

**Comment by H34D** [comment]
Some additional questions that just rose up on a chat with aitor:

- we need a clear definition of the purpose (e.g. Temporary contract that will be removed after day x, Safe harbour contract to swap tokens to, Anchor point for exchanges and single point of contact for token sale)
- how long will this stay on chain (or say active)?
- how does the migration to pacific look like?
- when will the migration happen?

**Comment by aaitor** [comment]
Description about the current behavior added in the README.md file:
https://github.com/oceanprotocol/ocean-token/blob/master/README.md

Further changes of scope must require the update of those specifications.
